models:
  - name: customers_stg
    description: Staged customer data for order management system
    columns:
      - name: Email
        tests:
          - string_not_empty
  - name: employees_stg
    columns:
      - name: JobTitle
        tests:
          - string_not_empty
  - name: orders_stg
    columns:
      - name: OrderID
        description: unique order id
        tests:
          - unique
          - not_null
      - name: StatusCD
        description: "{{ doc('StatusCD') }}"
        tests:
          - accepted_values:
              values: ['01', '02', '03']
  - name: orderitems_stg
    columns:
      - name: OrderID
        tests:
          - relationships:
              to: ref( 'orders_stg' )
              field: OrderID       